# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FU0zXu7JxL3zWdAvCfL9o1hsgrZdMp9m
"""

import pandas as pd

df = pd.read_csv('summer.csv')

df

"""#IN HOW MANY CITIES SUMMER OLYMPICS IS HELD SO FAR"""

df['City'].unique()

len(df['City'].unique())

"""#WHICH SPORT IS HAVING MORE NUMBER OF GOLD MEDALS SO FAR(TOP 5)"""

df[df['Medal']=='Gold']

df[df['Medal']=='Gold'].groupby("Sport").count()['Medal']

df[df['Medal']=='Gold'].groupby("Sport").count()['Medal'].sort_values(ascending = False)

df[df['Medal']=='Gold'].groupby("Sport").count()['Medal'].sort_values(ascending = False).head()

df[df['Medal']=='Gold'].groupby("Sport").count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(20,10))

"""#WHICH SPORT IS HAVING MOST NUMBER OF MEDALS SO FAR (TOP 5)"""

df.groupby("Sport").count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(20,10))

"""#WHICH SPORT IS HAVING MOST NUMBER OF MEDALS SO FAR"""

df['Athlete'].describe()

"""#WHICH PLAYER HAS WON MOST NUMBER OF GOLD MEDALS(TOP 5)"""

df[df['Medal']=='Gold'].groupby("Athlete").count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(20,10))

"""#IN WHICH YEAR INDIA WON THE FIRST GOLD MEDAL """

Ind_Gold=df[df['Country']=='IND']
Ind_Gold

Ind_Gold[Ind_Gold['Medal']=='Gold']['Year']

Ind_Gold[Ind_Gold['Medal']=='Gold']['Year'].min()

"""#WHICH EVENT IS MOST POPULAR IN TERMS ON NUMBER OF PLAYERS"""

df.groupby("Event").count()['Athlete'].sort_values(ascending = False).head().plot.bar(figsize=(20,10))



Wom=df[df['Gender']=='Women']

Wom[Wom['Medal']== 'Gold'].groupby('Sport').count()['Medal'].sort_values(ascending = False).plot.bar(figsize=(20,10))

Wom[Wom['Medal']== 'Gold'].groupby('Sport').count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(20,10))